/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    ButtonComponent: typeof import('./src/components/ButtonComponent.vue')['default']
    Card: typeof import('primevue/card')['default']
    CarouselComponent: typeof import('./src/components/CarouselComponent.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    DialogComponenet: typeof import('./src/components/DialogComponenet.vue')['default']
    Edit: typeof import('./src/components/icons/buttons/Edit.vue')['default']
    Error: typeof import('./src/components/icons/alert/error.vue')['default']
    EventMarkerSymbol: typeof import('./src/components/icons/EventMarkerSymbol.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    Form: typeof import('@primevue/forms/form')['default']
    Group: typeof import('./src/components/icons/menu/Group.vue')['default']
    Home: typeof import('./src/components/icons/menu/Home.vue')['default']
    InputComponent: typeof import('./src/components/InputComponent.vue')['default']
    InputMask: typeof import('primevue/inputmask')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('./src/components/icons/menu/Menu.vue')['default']
    Message: typeof import('primevue/message')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Textarea: typeof import('primevue/textarea')['default']
    Timeline: typeof import('primevue/timeline')['default']
    ToggleTheme: typeof import('./src/components/ToggleTheme.vue')['default']
    UserProfileForm: typeof import('./src/components/UserProfileForm.vue')['default']
  }
}
